# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ada632488166ec1eb24918f3db3f70f311ac76f2d6241d09f5e144d2dc37e8bed73c6b75c291a4c85b96978d2825a14b10f34e3807680eb8750223f9c8b5fa2

test:
  secret_key_base: 41737efb0db9e7fe03ef3b06def148717c8d4104ecfc5064c29763cb8b1c91ca437a064d581df361cb9ffe52d8c2e01a9f9fac27617d6c5983fb62c5a27f713b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
